---
- hosts: netbox
  gather_facts: False
  vars:
    ansible_python_interpreter: venv/bin/python3  
  module_defaults:
    group/netbox.netbox.netbox:
      validate_certs: False
      netbox_url: "{{ netbox_url }}"
      netbox_token: "{{ netbox_api_token }}"
  tasks:
    - name: Poke the api
      uri:
        url: "{{ netbox_url}}/api/"
        method: GET
        headers:
          Accept: application/json
          Authorization: "Token {{ netbox_api_token }}"

    - name: "Setup Sites"
      netbox.netbox.netbox_site:
        validate_certs: False
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_api_token }}"
        data: "{{ item }}"
      loop: "{{ site_list }}"


