---
netbox_api_token: "{{ vault_netbox_api_token }}" 
netbox_url: http://localhost:443
ansible_python_interpreter: /usr/bin/python3
prefixes:
  - Prefix: 10.102.10.0/24
    Tenant: vnet-arc-fgt-dev-eu1
site_list:
  - name: “NYC”
    time_zone: America/New_York
    status: Active
  - name: “CHI”
    time_zone: America/Chicago
    status: Active
  - name: “RTP”
    time_zone: America/New_York
    status: Active
manufacturers:
  - Dell
device_types:
  - model: “PowerEdge R340”
    manufacturer: “Dell”
    slug: “dell-poweredge-r340"
    part_number: 123
    full_depth: True
device_roles:
  - name: "Application Server"
    slug: "app-server"
    color: "Grey"
